### ISSUE TITLE
Description should be a LangStringSet

### ISSUE THREAD

**Issue by FrankSchnicke** [admin-shell-io/java-model#11] opened 2022-05-20 07:31 UTC
Right now, it is only a LangString

**Comment by sebbader** [comment] 2022-09-15 14:30
After longer discussions in the IDTA, the intended behaviour has been clarified: LangStringSet shall appear as an array of LangStrings in the serialisations, and therefore as a `List<LangString` in the java model. This has been implemented in e.g. https://github.com/eclipse-digitaltwin/aas4j/blob/001dcec40b23c27cfa576859e0168d20f51780b9/model/src/main/java/io/adminshell/aas/v3/model/Referable.java#L77
Therefore, I close the issue. @FrankSchnicke please open it again in https://github.com/eclipse-digitaltwin/aas4j/issues if you disagree.

**Closed as completed by sebbader** 2022-09-15 14:30 UTC
Labels: bug

**Comment by FrankSchnicke** [comment] 2022-09-15 14:39
Fine with me
